version: '3.9'

services:
  database:
    image: postgres:13.14
    restart: always
    environment:
      POSTGRES_DB: songmaket
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: