-- public.asset_banner definition

-- Drop table

-- DROP TABLE public.asset_banner;

CREATE TABLE public.asset_banner (
	id uuid NOT NULL,
	image varchar(100) NOT NULL,
	title varchar(255) NOT NULL,
	CONSTRAINT asset_banner_pkey PRIMARY KEY (id)
);


-- public.auth_group definition

-- Drop table

-- DROP TABLE public.auth_group;

CREATE TABLE public.auth_group (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(150) NOT NULL,
	CONSTRAINT auth_group_name_key UNIQUE (name),
	CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


-- public.django_content_type definition

-- Drop table

-- DROP TABLE public.django_content_type;

CREATE TABLE public.django_content_type (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app_label varchar(100) NOT NULL,
	model varchar(100) NOT NULL,
	CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model),
	CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);


-- public.django_migrations definition

-- Drop table

-- DROP TABLE public.django_migrations;

CREATE TABLE public.django_migrations (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	app varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	applied timestamptz NOT NULL,
	CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);


-- public.django_session definition

-- Drop table

-- DROP TABLE public.django_session;

CREATE TABLE public.django_session (
	session_key varchar(40) NOT NULL,
	session_data text NOT NULL,
	expire_date timestamptz NOT NULL,
	CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


-- public.socialaccount_socialapp definition

-- Drop table

-- DROP TABLE public.socialaccount_socialapp;

CREATE TABLE public.socialaccount_socialapp (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	provider varchar(30) NOT NULL,
	"name" varchar(40) NOT NULL,
	client_id varchar(191) NOT NULL,
	secret varchar(191) NOT NULL,
	"key" varchar(191) NOT NULL,
	provider_id varchar(200) NOT NULL,
	settings jsonb NOT NULL,
	CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id)
);


-- public.song_artist definition

-- Drop table

-- DROP TABLE public.song_artist;

CREATE TABLE public.song_artist (
	id uuid NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT song_artist_pkey PRIMARY KEY (id)
);


-- public."user" definition

-- Drop table

-- DROP TABLE public."user";

CREATE TABLE public."user" (
	"password" varchar(128) NOT NULL,
	last_login timestamptz NULL,
	is_superuser bool NOT NULL,
	username varchar(150) NOT NULL,
	first_name varchar(150) NOT NULL,
	last_name varchar(150) NOT NULL,
	email varchar(254) NOT NULL,
	is_staff bool NOT NULL,
	is_active bool NOT NULL,
	date_joined timestamptz NOT NULL,
	id uuid NOT NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id),
	CONSTRAINT user_username_key UNIQUE (username)
);
CREATE INDEX user_username_cf016618_like ON public."user" USING btree (username varchar_pattern_ops);


-- public.account_emailaddress definition

-- Drop table

-- DROP TABLE public.account_emailaddress;

CREATE TABLE public.account_emailaddress (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(254) NOT NULL,
	verified bool NOT NULL,
	"primary" bool NOT NULL,
	user_id uuid NOT NULL,
	CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id),
	CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email),
	CONSTRAINT account_emailaddress_user_id_2c513194_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX account_emailaddress_upper ON public.account_emailaddress USING btree (upper((email)::text));
CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);
CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


-- public.account_emailconfirmation definition

-- Drop table

-- DROP TABLE public.account_emailconfirmation;

CREATE TABLE public.account_emailconfirmation (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created timestamptz NOT NULL,
	sent timestamptz NULL,
	"key" varchar(64) NOT NULL,
	email_address_id int4 NOT NULL,
	CONSTRAINT account_emailconfirmation_key_key UNIQUE (key),
	CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id),
	CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);
CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


-- public.auth_permission definition

-- Drop table

-- DROP TABLE public.auth_permission;

CREATE TABLE public.auth_permission (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	content_type_id int4 NOT NULL,
	codename varchar(100) NOT NULL,
	CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename),
	CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
	CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


-- public.authtoken_token definition

-- Drop table

-- DROP TABLE public.authtoken_token;

CREATE TABLE public.authtoken_token (
	"key" varchar(40) NOT NULL,
	created timestamptz NOT NULL,
	user_id uuid NOT NULL,
	CONSTRAINT authtoken_token_pkey PRIMARY KEY (key),
	CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id),
	CONSTRAINT authtoken_token_user_id_35299eff_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


-- public.django_admin_log definition

-- Drop table

-- DROP TABLE public.django_admin_log;

CREATE TABLE public.django_admin_log (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	action_time timestamptz NOT NULL,
	object_id text NULL,
	object_repr varchar(200) NOT NULL,
	action_flag int2 NOT NULL,
	change_message text NOT NULL,
	content_type_id int4 NULL,
	user_id uuid NOT NULL,
	CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)),
	CONSTRAINT django_admin_log_pkey PRIMARY KEY (id),
	CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


-- public.socialaccount_socialaccount definition

-- Drop table

-- DROP TABLE public.socialaccount_socialaccount;

CREATE TABLE public.socialaccount_socialaccount (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	provider varchar(200) NOT NULL,
	uid varchar(191) NOT NULL,
	last_login timestamptz NOT NULL,
	date_joined timestamptz NOT NULL,
	extra_data jsonb NOT NULL,
	user_id uuid NOT NULL,
	CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id),
	CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid),
	CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


-- public.socialaccount_socialtoken definition

-- Drop table

-- DROP TABLE public.socialaccount_socialtoken;

CREATE TABLE public.socialaccount_socialtoken (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"token" text NOT NULL,
	token_secret text NOT NULL,
	expires_at timestamptz NULL,
	account_id int4 NOT NULL,
	app_id int4 NULL,
	CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id),
	CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id),
	CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);
CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


-- public.song_album definition

-- Drop table

-- DROP TABLE public.song_album;

CREATE TABLE public.song_album (
	id uuid NOT NULL,
	title varchar(255) NOT NULL,
	release_date date NOT NULL,
	artist_id uuid NOT NULL,
	CONSTRAINT song_album_pkey PRIMARY KEY (id),
	CONSTRAINT song_album_artist_id_50e8a6f4_fk_song_artist_id FOREIGN KEY (artist_id) REFERENCES public.song_artist(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX song_album_artist_id_50e8a6f4 ON public.song_album USING btree (artist_id);


-- public.song_playlist definition

-- Drop table

-- DROP TABLE public.song_playlist;

CREATE TABLE public.song_playlist (
	id uuid NOT NULL,
	title varchar(255) NOT NULL,
	user_id uuid NOT NULL,
	CONSTRAINT song_playlist_pkey PRIMARY KEY (id),
	CONSTRAINT song_playlist_user_id_e2836fab_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX song_playlist_user_id_e2836fab ON public.song_playlist USING btree (user_id);


-- public.user_groups definition

-- Drop table

-- DROP TABLE public.user_groups;

CREATE TABLE public.user_groups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id uuid NOT NULL,
	group_id int4 NOT NULL,
	CONSTRAINT user_groups_pkey PRIMARY KEY (id),
	CONSTRAINT user_groups_user_id_group_id_40beef00_uniq UNIQUE (user_id, group_id),
	CONSTRAINT user_groups_group_id_b76f8aba_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT user_groups_user_id_abaea130_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX user_groups_group_id_b76f8aba ON public.user_groups USING btree (group_id);
CREATE INDEX user_groups_user_id_abaea130 ON public.user_groups USING btree (user_id);


-- public.user_user_permissions definition

-- Drop table

-- DROP TABLE public.user_user_permissions;

CREATE TABLE public.user_user_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id uuid NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT user_user_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT user_user_permissions_user_id_permission_id_7dc6e2e0_uniq UNIQUE (user_id, permission_id),
	CONSTRAINT user_user_permission_permission_id_9deb68a3_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT user_user_permissions_user_id_ed4a47ea_fk_user_id FOREIGN KEY (user_id) REFERENCES public."user"(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX user_user_permissions_permission_id_9deb68a3 ON public.user_user_permissions USING btree (permission_id);
CREATE INDEX user_user_permissions_user_id_ed4a47ea ON public.user_user_permissions USING btree (user_id);


-- public.auth_group_permissions definition

-- Drop table

-- DROP TABLE public.auth_group_permissions;

CREATE TABLE public.auth_group_permissions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int4 NOT NULL,
	permission_id int4 NOT NULL,
	CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
	CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
	CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


-- public.song definition

-- Drop table

-- DROP TABLE public.song;

CREATE TABLE public.song (
	id uuid NOT NULL,
	title varchar(255) NOT NULL,
	audio varchar(100) NOT NULL,
	album_id uuid NULL,
	artist_id uuid NULL,
	image varchar(100) NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	view_count int4 NOT NULL,
	CONSTRAINT song_pkey PRIMARY KEY (id),
	CONSTRAINT song_album_id_87bc8638_fk_song_album_id FOREIGN KEY (album_id) REFERENCES public.song_album(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT song_artist_id_72f5be10_fk_song_artist_id FOREIGN KEY (artist_id) REFERENCES public.song_artist(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX song_album_id_87bc8638 ON public.song USING btree (album_id);
CREATE INDEX song_artist_id_72f5be10 ON public.song USING btree (artist_id);


-- public.song_playlist_songs definition

-- Drop table

-- DROP TABLE public.song_playlist_songs;

CREATE TABLE public.song_playlist_songs (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	playlist_id uuid NOT NULL,
	song_id uuid NOT NULL,
	CONSTRAINT song_playlist_songs_pkey PRIMARY KEY (id),
	CONSTRAINT song_playlist_songs_playlist_id_song_id_da28d56a_uniq UNIQUE (playlist_id, song_id),
	CONSTRAINT song_playlist_songs_playlist_id_653009ab_fk_song_playlist_id FOREIGN KEY (playlist_id) REFERENCES public.song_playlist(id) DEFERRABLE INITIALLY DEFERRED,
	CONSTRAINT song_playlist_songs_song_id_7ad21d2e_fk_song_id FOREIGN KEY (song_id) REFERENCES public.song(id) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX song_playlist_songs_playlist_id_653009ab ON public.song_playlist_songs USING btree (playlist_id);
CREATE INDEX song_playlist_songs_song_id_7ad21d2e ON public.song_playlist_songs USING btree (song_id);