# Generated by Django 5.0.2 on 2024-02-25 03:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/banners/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
    ]
