# Generated by Django 5.0.2 on 2024-02-25 09:19

import song.services.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(null=True, upload_to='songs/image/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(help_text='Upload a song file (mp3)', upload_to='songs/audio/', validators=[song.services.validator.validate_audio_file]),
        ),
    ]
